name:                fcl
version:             0.1.0.0
github:              adjoint-io/fcl
license:             Apache
author:              "Adjoint Inc."
maintainer:          "stephen@adjoint.io"
category:            Compiler
copyright:           "2016-2019 Adjoint Inc."

extra-source-files:
- README.md
- ChangeLog.md

description:         Financial Core Language compiler

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - text
  - memory
  - lattices

  # Data Structures
  - containers

  # Serialization
  - binary

  # Date & Time
  - time
  - datetimes
  - hourglass

  # Text
  - bytestring

ghc-options:
  -fwarn-tabs
  -fwarn-incomplete-patterns
  -fwarn-incomplete-uni-patterns
  -fwarn-incomplete-record-updates
  -fwarn-redundant-constraints
  -fwarn-implicit-prelude
  -fwarn-overflowed-literals
  -fwarn-orphans
  -fwarn-identities
  -fwarn-dodgy-exports
  -fwarn-dodgy-imports
  -fwarn-duplicate-exports
  -fwarn-overlapping-patterns
  -fwarn-missing-fields
  -fwarn-missing-methods
  -fwarn-missing-signatures
  -fwarn-noncanonical-monad-instances
  -fwarn-unused-imports
  -fwarn-unused-pattern-binds
  -fwarn-unused-type-patterns
  -fwarn-unrecognised-pragmas
  -fwarn-wrong-do-bind
  -fwarn-hi-shadowing
  -fno-warn-name-shadowing
  -fno-warn-unused-binds
  -fno-warn-unused-matches
  -fno-warn-unused-do-bind

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes

library:
  source-dirs: src
  dependencies:
  - deepseq
  - directory
  - filepath
  - unix
  - array
  - pretty-show
  - ansi-terminal
  - process-extras

  # Serialization
  - cereal
  - cereal-text
  - aeson
  - pretty-hex

  # Exceptions
  - exceptions

    # Control Structures
  - mtl
  - transformers

  # Text
  - text
  - parsec
  - wl-pprint-text
  - base58-bytestring

  # Cryptography
  - cryptonite
  - memory
  - pem
  - x509
  - asn1-types
  - asn1-encoding
  - arithmoi

  exposed-modules:
    - Language.FCL.Contract
    - Language.FCL.AST
    - Language.FCL.Delta
    - Numeric.Lossless.Decimal
    - Numeric.Lossless.Number
    - Language.FCL.Init
    - Language.FCL.Storage
    - Language.FCL.Pretty
    - Language.FCL.Error
    - Language.FCL.Eval
    - Language.FCL.Prim
    - Language.FCL.Token
    - Language.FCL.Lexer
    - Language.FCL.Parser
    - Language.FCL.Compile
    - Language.FCL.Typecheck
    - Language.FCL.LanguageServerProtocol
    - Language.FCL.Duplicate
    - Language.FCL.Undefinedness
    - Language.FCL.Effect
    - Language.FCL.WorkflowNet
    - Language.FCL.ReachabilityGraph
    - Language.FCL.Analysis
    - Language.FCL.Graphviz
    - Language.FCL.Hash
    - Language.FCL.Key
    - Language.FCL.Address
    - Language.FCL.Encoding
    - Language.FCL.Metadata
    - Language.FCL.Asset
    - Language.FCL.SafeString
    - Language.FCL.SafeInteger
    - Language.FCL.Unsafe
    - Language.FCL.Utils
    - Language.FCL.Time
    - Language.FCL.World
    - Language.FCL.Warning

executables:
  fcl:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl
    - optparse-applicative
    - aeson-pretty

  fcl-lsp:
    main: Main.hs
    source-dirs: lsp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl
    - wai-logger
    - scotty
    - aeson
    - swagger2

  fcl-api:
    main: Main.hs
    source-dirs: api
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl
    - warp
    - wai
    - aeson
    - swagger2
    - servant
    - servant-swagger
    - servant-swagger-ui
    - servant-server
tests:
  fcl-test:
    main:                Main.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl
    - filepath
    - Diff
    - strict
    - cryptonite
    - file-embed
    - tasty
    - tasty-hunit
    - tasty-golden
    - tasty-quickcheck
    - QuickCheck
