name:                fcl
version:             0.1.0.0
github:              adjoint-io/fcl
license:             Apache
author:              "Adjoint Inc."
maintainer:          "stephen@adjoint.io"
category:            Compiler
copyright:           "2016-2019 Adjoint Inc."
default-extensions:
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables

extra-source-files:
- README.md
- ChangeLog.md

description:         Financial Core Language compiler

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - text
  - memory
  - lattices

  # Data Structures
  - containers
  - ilist
  - insert-ordered-containers

  # Serialization
  - binary
  - cereal
  - aeson

  # Date & Time
  - time
  - datetimes
  - hourglass

  # Text
  - bytestring

  # Quickcheck
  - QuickCheck
  - quickcheck-instances

  # Http
  - wai
  - wai-cors
  - warp
  - servant
  - servant-server
  - servant-checked-exceptions
  - servant-swagger
  - servant-swagger-ui
  - swagger2

library:
  source-dirs: src
  dependencies:
  - deepseq
  - directory
  - filepath
  - unix
  - pretty-show
  - ansi-terminal
  - process-extras

  # Serialization
  - cereal-text
  - pretty-hex

  # Exceptions
  - exceptions

    # Control Structures
  - mtl
  - transformers

  # Text
  - text
  - parsec
  - wl-pprint-text
  - base58-bytestring

  # Cryptography
  - cryptonite
  - arithmoi
  - pem
  - x509
  - asn1-types
  - asn1-encoding

  ghc-options:
    -Werror
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-uni-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-imports
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fwarn-hi-shadowing
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind
    -Wmissing-export-lists

  exposed-modules:
    - Language.FCL.Contract
    - Language.FCL.AST
    - Language.FCL.Delta
    - Language.FCL.Init
    - Language.FCL.Storage
    - Language.FCL.Debug
    - Language.FCL.Pretty
    - Language.FCL.Error
    - Language.FCL.Eval
    - Language.FCL.Prim
    - Language.FCL.Token
    - Language.FCL.Lexer
    - Language.FCL.Parser
    - Language.FCL.Compile
    - Language.FCL.Typecheck
    - Language.FCL.LanguageServerProtocol
    - Language.FCL.Duplicate
    - Language.FCL.Undefinedness
    - Language.FCL.Effect
    - Language.FCL.WorkflowNet
    - Language.FCL.ReachabilityGraph
    - Language.FCL.Analysis
    - Language.FCL.Graphviz
    - Language.FCL.Hash
    - Language.FCL.Key
    - Language.FCL.Address
    - Language.FCL.Encoding
    - Language.FCL.Metadata
    - Language.FCL.Asset
    - Language.FCL.Utils
    - Language.FCL.Time
    - Language.FCL.World
    - Language.FCL.Warning
    - Language.FCL.Orphans

    - Numeric.Lossless.Decimal
    - Numeric.Lossless.Number

    - HTTP.FCL.API
    - HTTP.FCL.SwaggerSchema

executables:
  fcl:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl
    - optparse-applicative
    - aeson-pretty

  fcl-http:
    main: Main.hs
    source-dirs: http
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl

tests:
  fcl-test:
    main:                Main.hs
    source-dirs:
    - tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl
    - filepath
    - Diff
    - strict
    - cryptonite
    - tasty
    - tasty-hunit
    - tasty-golden
    - tasty-quickcheck
    - tasty-hspec
    - hspec
    - warp
    - quickcheck-instances
    - aeson-pretty
    - mtl
    - monad-gen
