name:                fcl
version:             0.1.0.0
github:              adjoint-io/fcl
license:             Apache
author:              "Adjoint Inc."
maintainer:          "stephen@adjoint.io"
category:            Compiler
copyright:           "2016-2019 Adjoint Inc."

extra-source-files:
- README.md
- ChangeLog.md

description:         Financial Core Language compiler

dependencies:
  - base >= 4.12 && < 5
  - protolude
  - text
  - array
  - deepseq
  - directory
  - filepath
  - unix
  - array
  - pretty-show
  - safe
  - scientific
  - filelock
  - ansi-terminal
  - rank1dynamic
  - lattices
  - memory
  - process-extras

  # Serialization
  - cereal
  - cereal-text
  - binary
  - aeson
  - aeson-pretty
  - pretty-hex

  # Exceptions
  - exceptions

    # Control Structures
  - mtl
  - transformers
  - transformers-base
  - monad-control
  - lifted-base
  # Date & Time
  - time
  - datetimes
  - hourglass
  # Text
  - text
  - bytestring
  - parsec
  - attoparsec
  - wl-pprint-text
  - base58-bytestring

  # Data Structures
  - containers
  - hashable
  - unordered-containers

  # Cryptography
  - cryptonite

library:
  source-dirs: src
  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-uni-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-imports
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fwarn-hi-shadowing
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances
    - FlexibleContexts
    - ScopedTypeVariables
    - RankNTypes

  exposed-modules:
    - Script
    - Delta
    - Contract
    - Encoding
    - Fixed
    - Hash
    - Ledger
    - SafeInteger
    - SafeString
    - Storage
    - Time
    - Utils
    - Script.Analysis
    - Script.Compile
    - Script.Duplicate
    - Script.Effect
    - Script.Error
    - Script.Eval
    - Script.Graphviz
    - Script.Init
    - Script.Lexer
    - Script.Parser
    - Script.Pretty
    - Script.Prim
    - Script.ReachabilityGraph
    - Script.Storage
    - Script.Token
    - Script.Typecheck
    - Script.Undefinedness
    - Script.Warning
    - Script.WorkflowNet

executables:
  fcl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl

tests:
  fcl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fcl
